[package]
name = "counter_tauri"
version = "0.1.0"
edition = "2021"

# authors.workspace = true
# repository.workspace = true
# edition.workspace = true
# license.workspace = true
# keywords.workspace = true
# rust-version.workspace = true
[lib]
name = "tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
anyhow.workspace = true
futures = "0.3.30"
lazy_static = "1.4.0"
reqwest = { version = "0.12.4", features = ["stream"] }
shared = { path = "../../shared" }
tauri = { version = "1.6", features = ["shell-open"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
