[package]
name = "pubky-homeserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
http = "1.1.0"
thiserror = "1.0.49"
bytes = "1.6.0"
tower_governor = "0.4.2"
governor = "0.6.3"
heed = { version = "0.20.0", default-features = false }
serde = { version = "1.0.199", features = ["derive"] }
toml = "0.8.12"
clap = { version = "4.5.1", features = ["derive"] }
dirs-next = "2.0.0"
tower-sessions = "0.12.2"
